version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: vendor/bin/phpunit tests
      - run: cd ./tools/create-phar/ && ./create.sh && cd ./../../
      - store_artifacts:
          path: ./tools/create-phar/gtfs-merger
          prefix: build